import Image from "next/image";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { WorldcupStartButton } from "./WorldcupStartButton";
import { foodWinnerStats, foodWorldcupItems } from "@/data/food-worldcup";
import { JsonLd } from "@/components/seo/JsonLd";
import { absoluteUrl } from "@/lib/site";

export function WorldcupIntro() {
  const featured = [foodWorldcupItems[1],foodWorldcupItems[3],foodWorldcupItems[16]];
  return <div className="container-page py-8 sm:py-14"><Breadcrumbs items={[{name:"테스트",href:"/tests"},{name:"배달음식 월드컵"}]} /><div className="mx-auto max-w-4xl"><section className="overflow-hidden rounded-[2rem] border border-orange-100 bg-white shadow-card"><div className="relative h-72 overflow-hidden sm:h-96">{featured.map((item,index)=><div key={item.slug} className={`absolute top-0 h-full w-[46%] overflow-hidden ${index===0?"left-0 -rotate-3":index===1?"left-[27%] z-10 scale-105":"right-0 rotate-3"}`}><Image src={item.image} alt={item.name} fill sizes="(max-width:768px) 46vw, 360px" className="object-cover" priority={index===1} /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><span className="absolute bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap text-lg font-black text-white">{item.name}</span></div>)}</div><div className="p-6 text-center sm:p-10"><div className="flex flex-wrap justify-center gap-2"><span className="rounded-full bg-orange-50 px-3 py-1.5 text-xs font-black text-orange-600">음식</span><span className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-black text-violet-600">심리</span><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-600">라이프스타일</span></div><h1 className="mt-5 text-3xl font-black tracking-[-0.04em] text-ink sm:text-5xl">주말 배달음식 월드컵</h1><p className="mx-auto mt-4 max-w-xl leading-7 text-slate-600">두 음식 중 지금 더 당기는 메뉴를 선택하세요. 32강부터 결승까지, 고민하다 보면 오늘의 배달 메뉴가 자연스럽게 결정됩니다.</p><div className="mx-auto mt-7 max-w-md"><WorldcupStartButton /></div><div className="mt-5 flex flex-wrap justify-center gap-4 text-xs font-bold text-slate-400"><span>✓ 32개 메뉴</span><span>✓ 랜덤 대진</span><span>✓ 약 3분</span></div></div></section>
    <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-card sm:p-8"><h2 className="text-xl font-black text-ink">이번 주 우승 TOP5</h2><p className="mt-2 text-xs text-slate-400">현재 서비스 기준 예시 통계입니다.</p><ol className="mt-5 space-y-3">{foodWinnerStats.map((item,index)=><li key={item.name} className="flex items-center gap-3"><span className="w-7 text-lg">{["🥇","🥈","🥉","🏅","🏅"][index]}</span><span className="text-xl">{item.emoji}</span><strong className="min-w-16 text-sm text-ink">{item.name}</strong><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-orange-400 to-rose-500" style={{width:`${item.value*3.4}%`}} /></div><span className="w-9 text-right text-xs font-black text-orange-600">{item.value}%</span></li>)}</ol></section>
  </div><JsonLd data={{"@context":"https://schema.org","@type":"WebApplication",name:"주말 배달음식 월드컵",description:"32강 월드컵으로 오늘 가장 먹고 싶은 배달음식을 선택해보세요.",url:absoluteUrl("/tests/weekend-food-worldcup"),applicationCategory:"GameApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"KRW"}}} /></div>;
}
