import{ATEEZ_QUIZ_SIZE,ateezQuestions,ateezQuota,getAteezGrade,getAteezQuestion}from"@/data/ateez-fan";import type{AteezDifficulty,AteezQuestion}from"@/data/ateez-fan";
export type AteezPresentedQuestion=Omit<AteezQuestion,"question"|"options">&{originalId:string;prompt:string;choices:string[];optionOrder:number[]};export type AteezAnswer={questionId:string;choice:number};
function hash(seed:string){let v=2166136261;for(let i=0;i<seed.length;i++)v=Math.imul(v^seed.charCodeAt(i),16777619);return v>>>0;}function rng(seed:string){let s=hash(seed)||1;return()=>{s+=0x6d2b79f5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;};}export function seededAteezShuffle<T>(items:readonly T[],seed:string){const r=rng(seed),a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function ateezAlbumKey(q:AteezQuestion){const id=q.sourceIds[0];return id?.replace(/^SRC_/,"").replace(/_(SPOTIFY|KQ|REPORT|OVERVIEW)$/g,"")??null;}
function valid(items:AteezQuestion[],categoryMax=4){const categories=new Map<string,number>(),albums=new Map<string,number>();for(const q of items){categories.set(q.category,(categories.get(q.category)??0)+1);const key=ateezAlbumKey(q);if(key)albums.set(key,(albums.get(key)??0)+1);}return Math.max(...categories.values())<=categoryMax&&[...albums.values()].every(n=>n<=3)&&items.filter(q=>q.freshness==="time_sensitive").length<=3;}
function pick(seed:string,attempt:number){return(Object.keys(ateezQuota)as AteezDifficulty[]).flatMap(d=>seededAteezShuffle(ateezQuestions.filter(q=>q.difficulty===d),`${seed}:${attempt}:${d}`).slice(0,ateezQuota[d]));}
export function createAteezSession(seed:string):AteezPresentedQuestion[]{let selected:AteezQuestion[]|null=null;for(let attempt=0;attempt<150;attempt++){const candidate=pick(seed,attempt);if(valid(candidate,attempt<100?4:5)){selected=candidate;break;}}if(!selected)throw new Error("ATEEZ 퀴즈 세션 생성 실패");return seededAteezShuffle(selected,`${seed}:questions`).map(q=>{const optionOrder=seededAteezShuffle([0,1,2,3],`${seed}:${q.id}:options`);return{...q,originalId:q.id,prompt:q.question,choices:optionOrder.map(i=>q.options[i]),optionOrder};});}
export function calculateAteezResult(answers:AteezAnswer[]){const reviews=answers.flatMap(a=>{const question=getAteezQuestion(a.questionId);return question?[{question,choice:a.choice,correct:a.choice===question.answerIndex}]:[];});const score=reviews.filter(r=>r.correct).length;const byDifficulty=(Object.keys(ateezQuota)as AteezDifficulty[]).map(difficulty=>({difficulty,total:ateezQuota[difficulty],correct:reviews.filter(r=>r.question.difficulty===difficulty&&r.correct).length}));return{score,accuracy:Math.round(score/ATEEZ_QUIZ_SIZE*100),grade:getAteezGrade(score),reviews,byDifficulty};}
export function encodeAteezAnswers(answers:AteezAnswer[]){return answers.map(a=>`${a.questionId}.${a.choice}`).join("-");}export function parseAteezAnswers(raw?:string):AteezAnswer[]|null{if(!raw)return null;const answers=raw.split("-").map(token=>{const[questionId,choice]=token.split(".");return{questionId,choice:Number(choice)};});return answers.length===ATEEZ_QUIZ_SIZE&&new Set(answers.map(a=>a.questionId)).size===ATEEZ_QUIZ_SIZE&&answers.every(a=>getAteezQuestion(a.questionId)&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<4)?answers:null;}
