import { BIGBANG_QUIZ_SIZE, bigbangQuestions, bigbangQuota, getBigbangGrade, getBigbangQuestion } from "@/data/bigbang-fan";
import type { BigbangDifficulty, BigbangQuestion } from "@/data/bigbang-fan";
export type BigbangPresentedQuestion = Omit<BigbangQuestion,"question"|"options"> & { originalId:string; prompt:string; choices:string[]; optionOrder:number[] };
export type BigbangAnswer = { questionId:string; choice:number };
function hash(seed:string){let v=2166136261;for(let i=0;i<seed.length;i++)v=Math.imul(v^seed.charCodeAt(i),16777619);return v>>>0;}
function rng(seed:string){let s=hash(seed)||1;return()=>{s+=0x6d2b79f5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;};}
export function seededBigbangShuffle<T>(items:readonly T[],seed:string){const r=rng(seed),a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const madeGroups=new Set(["made_m","made_a","made_d","made_e","made_full"]);
function valid(items:BigbangQuestion[],relax=0){const topics=new Set(items.map(q=>q.topicGroup));if(topics.size!==items.length)return false;const count=(category:string)=>items.filter(q=>q.category===category).length;return count("release_date")<=3+relax&&count("concert")<=1+relax&&count("solo_track")<=2+relax&&items.filter(q=>madeGroups.has(q.topicGroup)).length<=4+relax;}
function pick(seed:string,attempt:number,recentIds:string[]){const chosen:BigbangQuestion[]=[];for(const difficulty of Object.keys(bigbangQuota) as BigbangDifficulty[]){const pool=seededBigbangShuffle(bigbangQuestions.filter(q=>q.difficulty===difficulty),`${seed}:${attempt}:${difficulty}`);const ordered=[...pool.filter(q=>!recentIds.includes(q.id)),...pool.filter(q=>recentIds.includes(q.id))];for(const q of ordered){if(chosen.some(x=>x.topicGroup===q.topicGroup))continue;chosen.push(q);if(chosen.filter(x=>x.difficulty===difficulty).length===bigbangQuota[difficulty])break;}}return chosen;}
export function createBigbangSession(seed:string,recentIds:string[]=[]):BigbangPresentedQuestion[]{let selected:BigbangQuestion[]|null=null;for(let attempt=0;attempt<450;attempt++){const candidate=pick(seed,attempt,recentIds);const relax=attempt<250?0:attempt<350?1:2;if(candidate.length===BIGBANG_QUIZ_SIZE&&valid(candidate,relax)){selected=candidate;break;}}if(!selected)throw new Error("BIGBANG 퀴즈 세션 생성 실패");return seededBigbangShuffle(selected,`${seed}:questions`).map(q=>{const optionOrder=seededBigbangShuffle([0,1,2,3],`${seed}:${q.id}:options`);return{...q,originalId:q.id,prompt:q.question,choices:optionOrder.map(i=>q.options[i]),optionOrder};});}
export function calculateBigbangResult(answers:BigbangAnswer[]){const reviews=answers.flatMap(a=>{const question=getBigbangQuestion(a.questionId);return question?[{question,choice:a.choice,correct:a.choice===question.answerIndex}]:[];});const score=reviews.filter(r=>r.correct).length;const byDifficulty=(Object.keys(bigbangQuota) as BigbangDifficulty[]).map(difficulty=>({difficulty,total:bigbangQuota[difficulty],correct:reviews.filter(r=>r.question.difficulty===difficulty&&r.correct).length}));return{score,accuracy:Math.round(score/BIGBANG_QUIZ_SIZE*100),grade:getBigbangGrade(score),reviews,byDifficulty};}
export const encodeBigbangAnswers=(answers:BigbangAnswer[])=>answers.map(a=>`${a.questionId}.${a.choice}`).join("-");
export function parseBigbangAnswers(raw?:string):BigbangAnswer[]|null{if(!raw)return null;const answers=raw.split("-").map(token=>{const[questionId,choice]=token.split(".");return{questionId,choice:Number(choice)};});return answers.length===BIGBANG_QUIZ_SIZE&&new Set(answers.map(a=>a.questionId)).size===BIGBANG_QUIZ_SIZE&&answers.every(a=>getBigbangQuestion(a.questionId)&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<4)?answers:null;}
