import { idealDimensions, idealProfiles, idealQuestions, type IdealCategory, type IdealDimension, type IdealProfile, type IdealQuestion, type IdealScores, type UserGender } from "@/data/ideal-type";
const dimensions = idealDimensions.map(([key]) => key) as IdealDimension[];
const categories: IdealCategory[] = ["emotionalSecurity", "communication", "lifestyleRhythm", "growthAndStability", "relationshipDistance", "visualStyle"];
function rng(seed: number) { let state = Math.abs(seed) || 1; return () => { state = (state * 1664525 + 1013904223) % 4294967296; return state / 4294967296; }; }
function shuffle<T>(items: T[], next: () => number) { const copy = [...items]; for (let index = copy.length - 1; index > 0; index -= 1) { const target = Math.floor(next() * (index + 1)); [copy[index], copy[target]] = [copy[target], copy[index]]; } return copy; }
export type IdealSessionQuestion = IdealQuestion & { optionOrder: string[] };
export function selectIdealQuestions(branch: UserGender, seed: number) { const next = rng(seed); const selected: IdealQuestion[] = []; const usedTags = new Set<string>(); categories.forEach((category) => { const candidates = shuffle(idealQuestions.filter((question) => question.branch === branch && question.category === category), next); for (const question of candidates) { if (selected.filter((item) => item.category === category).length >= 2) break; const sceneTags = question.tags.filter((tag) => tag.startsWith("scene-")); if (sceneTags.some((tag) => usedTags.has(tag))) continue; selected.push(question); sceneTags.forEach((tag) => usedTags.add(tag)); } }); return shuffle(selected, next).map((question) => ({ ...question, optionOrder: shuffle(question.options.map((option) => option.id), next) })); }
export function calculateIdealScores(questions: IdealSessionQuestion[], answers: Record<string, string>) { const raw = Object.fromEntries(dimensions.map((key) => [key, 0])) as IdealScores; const min = Object.fromEntries(dimensions.map((key) => [key, 0])) as IdealScores; const max = Object.fromEntries(dimensions.map((key) => [key, 0])) as IdealScores; questions.forEach((question) => { const selected = question.options.find((option) => option.id === answers[question.id]); dimensions.forEach((key) => { const values = question.options.map((option) => option.scores[key] ?? 0); min[key] += Math.min(...values); max[key] += Math.max(...values); raw[key] += selected?.scores[key] ?? 0; }); }); return Object.fromEntries(dimensions.map((key) => [key, max[key] === min[key] ? 50 : Math.round(((raw[key] - min[key]) / (max[key] - min[key])) * 100)])) as IdealScores; }
const weighted = ["warmth", "affectionExpression", "communicationDirectness", "conflictRecovery", "socialEnergy", "spontaneity", "achievementOrientation", "lifestyleStability", "intimacyNeed", "independenceNeed", "softStrongAura", "styleExpressiveness"] as IdealDimension[];
export function matchIdealProfile(branch: UserGender, scores: IdealScores) { const candidates = idealProfiles.filter((profile) => profile.targetGender === (branch === "male" ? "female" : "male")); const ranked = candidates.map((profile) => ({ profile, distance: Math.sqrt(weighted.reduce((sum, key) => sum + (scores[key] - profile.vector[key]) ** 2, 0) / weighted.length) })).sort((left, right) => left.distance - right.distance || left.profile.id.localeCompare(right.profile.id)); const best = ranked[0]; const match = Math.round(Math.max(55, 100 - best.distance)); const clarity = Math.round(Math.min(100, Math.max(0, (ranked[1].distance - best.distance) * 6 + 45))); return { profile: best.profile, secondary: ranked.slice(1, 3).map((item) => item.profile), match, clarity }; }
export function areaScores(scores: IdealScores) { return { "정서적 안정감": Math.round((scores.warmth + scores.affectionExpression) / 2), "소통 방식": Math.round((scores.communicationDirectness + scores.conflictRecovery) / 2), "생활 리듬": Math.round((scores.socialEnergy + scores.spontaneity) / 2), "성장과 안정": Math.round((scores.achievementOrientation + scores.lifestyleStability) / 2), "관계의 거리": Math.round((scores.intimacyNeed + scores.independenceNeed) / 2), "외적 분위기와 스타일": Math.round((scores.softStrongAura + scores.styleExpressiveness) / 2) }; }
