import { MANCHESTER_UNITED_MAX_SCORE, MANCHESTER_UNITED_QUIZ_SIZE, getManchesterUnitedGrade, getManchesterUnitedQuestion, manchesterUnitedQuestions, manchesterUnitedQuota, manchesterUnitedWeights } from "@/data/manchester-united-fan";
import type { ManchesterUnitedDifficulty, ManchesterUnitedQuestion } from "@/data/manchester-united-fan";
export type ManchesterUnitedPresentedQuestion = Omit<ManchesterUnitedQuestion, "question" | "options"> & { originalId: string; prompt: string; choices: string[]; optionOrder: number[] };
export type ManchesterUnitedAnswer = { questionId: string; choice: number };
function hash(seed: string) { let v = 2166136261; for (let i=0;i<seed.length;i++) v=Math.imul(v^seed.charCodeAt(i),16777619); return v>>>0; }
function rng(seed:string){let s=hash(seed)||1;return()=>{s+=0x6d2b79f5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;};}
export function seededManchesterUnitedShuffle<T>(items:readonly T[],seed:string){const r=rng(seed),next=[...items];for(let i=next.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[next[i],next[j]]=[next[j],next[i]];}return next;}
function distribution(items:ManchesterUnitedQuestion[]){const categories=new Map<string,number>(),eras=new Map<string,number>(),answers=new Map<string,number>();for(const q of items){categories.set(q.category,(categories.get(q.category)??0)+1);eras.set(q.era,(eras.get(q.era)??0)+1);answers.set(q.answer,(answers.get(q.answer)??0)+1);}return{categories,eras,answers};}
function valid(items:ManchesterUnitedQuestion[],level=0){const {categories,eras,answers}=distribution(items);const max=4+level;return Math.max(...categories.values())<=max&&Math.max(...eras.values())<=max&&categories.size>=Math.max(6-level,4)&&eras.size>=Math.max(5-level,3)&&Math.max(...answers.values())<=2;}
function pick(seed:string,attempt:number){return(Object.keys(manchesterUnitedQuota)as ManchesterUnitedDifficulty[]).flatMap(d=>seededManchesterUnitedShuffle(manchesterUnitedQuestions.filter(q=>q.difficulty===d),`${seed}:${attempt}:${d}`).slice(0,manchesterUnitedQuota[d]));}
export function createManchesterUnitedSession(seed:string):ManchesterUnitedPresentedQuestion[]{let selected:ManchesterUnitedQuestion[]|null=null;for(let level=0;level<=2&&!selected;level++){for(let attempt=0;attempt<100;attempt++){const candidate=pick(seed,level*100+attempt);if(valid(candidate,level)){selected=candidate;break;}}}if(!selected)throw new Error("맨유 퀴즈 세션 생성 실패");return seededManchesterUnitedShuffle(selected,`${seed}:questions`).map(q=>{const optionOrder=seededManchesterUnitedShuffle([0,1,2,3],`${seed}:${q.id}:options`);return{...q,originalId:q.id,prompt:q.question,choices:optionOrder.map(i=>q.options[i]),optionOrder};});}
export function calculateManchesterUnitedResult(answers:ManchesterUnitedAnswer[]){const reviews=answers.flatMap(a=>{const question=getManchesterUnitedQuestion(a.questionId);return question?[{question,choice:a.choice,correct:a.choice===question.answerIndex}]:[];});const score=reviews.filter(r=>r.correct).length;const weightedScore=reviews.filter(r=>r.correct).reduce((sum,r)=>sum+manchesterUnitedWeights[r.question.difficulty],0);const byDifficulty=(Object.keys(manchesterUnitedQuota)as ManchesterUnitedDifficulty[]).map(difficulty=>({difficulty,total:manchesterUnitedQuota[difficulty],correct:reviews.filter(r=>r.question.difficulty===difficulty&&r.correct).length}));return{score,weightedScore,accuracy:Math.round(weightedScore/MANCHESTER_UNITED_MAX_SCORE*100),grade:getManchesterUnitedGrade(weightedScore),reviews,byDifficulty};}
export function encodeManchesterUnitedAnswers(answers:ManchesterUnitedAnswer[]){return answers.map(a=>`${a.questionId}.${a.choice}`).join("-");}
export function parseManchesterUnitedAnswers(raw?:string):ManchesterUnitedAnswer[]|null{if(!raw)return null;const answers=raw.split("-").map(token=>{const[questionId,choice]=token.split(".");return{questionId,choice:Number(choice)};});return answers.length===MANCHESTER_UNITED_QUIZ_SIZE&&new Set(answers.map(a=>a.questionId)).size===MANCHESTER_UNITED_QUIZ_SIZE&&answers.every(a=>getManchesterUnitedQuestion(a.questionId)&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<4)?answers:null;}
