import{NCT_DREAM_MAX_SCORE,NCT_DREAM_QUIZ_SIZE,getNctDreamGrade,getNctDreamQuestion,nctDreamQuestions,nctDreamQuota}from"@/data/nct-dream-fan";import type{NctDreamDifficulty,NctDreamQuestion}from"@/data/nct-dream-fan";
export type NctDreamPresentedQuestion=Omit<NctDreamQuestion,"question"|"choices">&{originalId:string;prompt:string;choices:string[];optionOrder:number[]};export type NctDreamAnswer={questionId:string;choice:number};
function hash(seed:string){let v=2166136261;for(let i=0;i<seed.length;i++)v=Math.imul(v^seed.charCodeAt(i),16777619);return v>>>0;}function rng(seed:string){let s=hash(seed)||1;return()=>{s+=0x6d2b79f5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296;};}export function seededNctDreamShuffle<T>(items:readonly T[],seed:string){const r=rng(seed),a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const identity=new Set(["멤버","그룹 역사","팬덤"]),music=new Set(["앨범","노래","수록곡"]),special=new Set(["공연","일본 활동","특별 활동"]);const countGroup=(items:NctDreamQuestion[],set:Set<string>)=>items.filter(q=>set.has(q.category)).length;const isTrack=(q:NctDreamQuestion)=>q.category==="수록곡"||/(track|order|opening|last_track)/i.test(q.factGroup);
function valid(items:NctDreamQuestion[],relaxed=false){const facts=new Set(items.map(q=>q.factGroup));if(facts.size!==items.length)return false;const topics=new Map<string,number>();for(const q of items)topics.set(q.topicKey,(topics.get(q.topicKey)??0)+1);if([...topics.values()].some(n=>n>2))return false;const a=countGroup(items,identity),b=countGroup(items,music),c=countGroup(items,special),tracks=items.filter(isTrack).length;return relaxed?a>=2&&c>=2&&tracks<=6:a>=2&&a<=4&&b>=8&&b<=11&&c>=2&&c<=4&&tracks<=5;}
function candidate(seed:string,attempt:number,recent:string[]){return(Object.keys(nctDreamQuota)as NctDreamDifficulty[]).flatMap(d=>{const pool=seededNctDreamShuffle(nctDreamQuestions.filter(q=>q.difficulty===d),`${seed}:${attempt}:${d}`);const ordered=[...pool.filter(q=>!recent.includes(q.id)),...pool.filter(q=>recent.includes(q.id))];return ordered.slice(0,nctDreamQuota[d]);});}
export function createNctDreamSession(seed:string,recent:string[]=[]):NctDreamPresentedQuestion[]{let selected:NctDreamQuestion[]|null=null;for(let attempt=0;attempt<2500;attempt++){const picked=candidate(seed,attempt,recent);if(valid(picked,attempt>=1800)){selected=picked;break;}}if(!selected)throw new Error("NCT DREAM 퀴즈 세션 생성 실패");return seededNctDreamShuffle(selected,`${seed}:questions`).map(q=>{const optionOrder=seededNctDreamShuffle([0,1,2,3],`${seed}:${q.id}:options`);return{...q,originalId:q.id,prompt:q.question,choices:optionOrder.map(i=>q.choices[i]),optionOrder};});}
export function calculateNctDreamResult(answers:NctDreamAnswer[]){const reviews=answers.flatMap(a=>{const question=getNctDreamQuestion(a.questionId);return question?[{question,choice:a.choice,correct:a.choice===question.answerIndex}]:[];});const correctCount=reviews.filter(r=>r.correct).length,score=reviews.filter(r=>r.correct).reduce((sum,r)=>sum+r.question.weight,0);const byDifficulty=(Object.keys(nctDreamQuota)as NctDreamDifficulty[]).map(difficulty=>({difficulty,total:nctDreamQuota[difficulty],correct:reviews.filter(r=>r.question.difficulty===difficulty&&r.correct).length}));return{score,correctCount,percentage:Math.round(score/NCT_DREAM_MAX_SCORE*100),grade:getNctDreamGrade(score),reviews,byDifficulty};}
export const encodeNctDreamAnswers=(answers:NctDreamAnswer[])=>answers.map(a=>`${a.questionId}.${a.choice}`).join("-");export function parseNctDreamAnswers(raw?:string):NctDreamAnswer[]|null{if(!raw)return null;const answers=raw.split("-").map(token=>{const[questionId,choice]=token.split(".");return{questionId,choice:Number(choice)};});return answers.length===NCT_DREAM_QUIZ_SIZE&&new Set(answers.map(a=>a.questionId)).size===NCT_DREAM_QUIZ_SIZE&&answers.every(a=>getNctDreamQuestion(a.questionId)&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<4)?answers:null;}
