import{getWorkPersonaResult,workPersonaQuestions}from"@/data/work-persona";import type{WorkAxis,WorkLetter,WorkOption,WorkPairGroup,WorkQuestion}from"@/data/work-persona";
export const WORK_PAIRS:WorkPairGroup[]=["EI_SN","EI_TF","EI_JP","SN_TF","SN_JP","TF_JP"],WORK_AXES:WorkAxis[]=["EI","SN","TF","JP"];export type WorkAnswer={questionId:string;scoreCode:string};export type PresentedWorkQuestion=Omit<WorkQuestion,"options">&{options:(WorkOption&{originalIndex:number})[]};export type WorkScores=Record<WorkLetter,number>;
function hash(seed:string){let v=2166136261;for(let i=0;i<seed.length;i++)v=Math.imul(v^seed.charCodeAt(i),16777619);return v>>>0}function rng(seed:string){let s=hash(seed)||1;return()=>{s+=0x6d2b79f5;let v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296}}export function seededWorkShuffle<T>(items:readonly T[],seed:string){const r=rng(seed),a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}const present=(q:WorkQuestion,seed:string):PresentedWorkQuestion=>({...q,options:seededWorkShuffle(q.options.map((o,i)=>({...o,originalIndex:i})),`${seed}:${q.id}:options`)});
function initialCandidate(seed:string,attempt:number){return WORK_PAIRS.flatMap((group,g)=>{const pool=seededWorkShuffle(workPersonaQuestions.filter(q=>q.pairGroup===group),`${seed}:${attempt}:${group}`);const preferred=pool.filter(q=>q.discriminationLevel===((g+attempt)%3)+1);const first=preferred[0]??pool[0],second=pool.find(q=>q.id!==first.id&&q.discriminationLevel!==first.discriminationLevel)??pool.find(q=>q.id!==first.id)!;return[first,second]})}function initialValid(items:WorkQuestion[]){const contexts=new Map<string,number>();for(const q of items)contexts.set(q.contextTag,(contexts.get(q.contextTag)??0)+1);const levels=[1,2,3].map(level=>items.filter(q=>q.discriminationLevel===level).length);return Math.max(...contexts.values())<3&&Math.min(...levels)>=2}
export function createWorkInitial(seed:string){for(let attempt=0;attempt<100;attempt++){const picked=initialCandidate(seed,attempt);if(initialValid(picked))return seededWorkShuffle(picked,`${seed}:initial`).map(q=>present(q,seed))}return seededWorkShuffle(initialCandidate(seed,101),`${seed}:initial`).map(q=>present(q,seed))}
export function scoreWorkAnswers(answers:WorkAnswer[]):WorkScores{const scores={E:0,I:0,S:0,N:0,T:0,F:0,J:0,P:0};for(const answer of answers)for(const letter of answer.scoreCode)scores[letter as WorkLetter]++;return scores}
export function selectAnchor(scores:WorkScores,seed:string):WorkAxis{const margins:Record<WorkAxis,number>={EI:Math.abs(scores.E-scores.I),SN:Math.abs(scores.S-scores.N),TF:Math.abs(scores.T-scores.F),JP:Math.abs(scores.J-scores.P)},min=Math.min(...Object.values(margins)),rotation=hash(`${seed}:anchor`)%4;return[...WORK_AXES.slice(rotation),...WORK_AXES.slice(0,rotation)].find(axis=>margins[axis]===min)!}
export function createWorkBoosters(seed:string,initial:PresentedWorkQuestion[],answers:WorkAnswer[]){const anchor=selectAnchor(scoreWorkAnswers(answers),seed),used=new Set(initial.map(q=>q.id)),contexts=new Set(initial.map(q=>q.contextTag)),groups=WORK_PAIRS.filter(g=>g.includes(anchor));const picked=groups.map((group,index)=>{const pool=seededWorkShuffle(workPersonaQuestions.filter(q=>q.pairGroup===group&&!used.has(q.id)),`${seed}:booster:${anchor}:${group}:${index}`),question=pool.find(q=>!contexts.has(q.contextTag))??pool[0];used.add(question.id);return present(question,seed)});return{anchor,questions:picked}}
export function calculateWorkResult(answers:WorkAnswer[]){const scores=scoreWorkAnswers(answers),typeCode=`${scores.E>scores.I?"E":"I"}${scores.S>scores.N?"S":"N"}${scores.T>scores.F?"T":"F"}${scores.J>scores.P?"J":"P"}`,profile=getWorkPersonaResult(typeCode)!;const tendencies=WORK_AXES.map(axis=>{const[a,b]=axis.split("")as[WorkLetter,WorkLetter],total=scores[a]+scores[b],letter=scores[a]>scores[b]?a:b,percentage=Math.round(Math.max(scores[a],scores[b])/total*100),label=percentage<=57?"두 성향이 비교적 균형적":percentage<=66?"약한 경향":percentage<=79?"뚜렷한 경향":"매우 뚜렷한 경향";return{axis,letter,percentage,label,left:{letter:a,score:scores[a]},right:{letter:b,score:scores[b]}}});return{scores,typeCode,profile,tendencies}}
export function compareWorkTypes(baseline:string,result:string){const matches=[0,1,2,3].filter(i=>baseline[i]===result[i]).length,description=matches===4?"평소와 회사에서 비교적 일관된 편":matches===3?"일부 업무 방식이 상황에 맞게 조정되는 편":matches===2?"역할에 따라 여러 성향을 균형 있게 사용하는 편":"회사 환경에서 역할 적응이 크게 나타나는 편";return{matches,description}}
export const encodeWorkAnswers=(answers:WorkAnswer[])=>answers.map(a=>`${a.questionId}.${a.scoreCode}`).join("-");export function parseWorkAnswers(raw?:string){if(!raw)return null;const answers=raw.split("-").map(token=>{const[questionId,scoreCode]=token.split(".");return{questionId,scoreCode}});return answers.length===15&&new Set(answers.map(a=>a.questionId)).size===15&&answers.every(a=>{const q=workPersonaQuestions.find(x=>x.id===a.questionId);return q?.options.some(o=>o.scoreCode===a.scoreCode)})?answers:null}
