import Link from "next/link";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { SectionReveal } from "@/components/motion/SectionReveal";
import { ShareButtons } from "@/components/share/ShareButtons";
import { ShareImageCard } from "@/components/share/ShareImageCard";
import { MobileShareDock } from "@/components/share/MobileShareDock";
import type { ConsumerDomainScores, ConsumerResultProfile } from "@/lib/types";

const domains=[{key:"planning",label:"계획성",hint:"예산과 비교를 바탕으로 결정하는 힘"},{key:"impulsivity",label:"충동성",hint:"감정과 즉각적인 자극에 반응하는 정도"},{key:"experience",label:"경험 선호",hint:"소유보다 여행·취미·체험을 중시하는 정도"},{key:"future",label:"미래 지향성",hint:"현재 소비를 장기 목표와 연결하는 정도"},{key:"quality",label:"품질 추구",hint:"가격보다 완성도와 사용 가치를 중시하는 정도"}] as const;

export function ConsumerStyleResult({profile,fitScore,areaScores,secondary}:{profile:ConsumerResultProfile;fitScore:number;areaScores:ConsumerDomainScores;secondary?:ConsumerResultProfile}){
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#e0e7ff_0,#f8fafc_36%,#f8fafc_100%)] pb-24 pt-8 sm:py-14"><div className="container-page"><Breadcrumbs items={[{name:"테스트",href:"/tests"},{name:"소비성향 결과"}]} /><div className="mx-auto max-w-4xl">
    <SectionReveal><section className="overflow-hidden rounded-[2rem] border border-white bg-white/90 text-center shadow-2xl shadow-indigo-100/70 backdrop-blur"><div className="bg-gradient-to-b from-indigo-50 via-violet-50/50 to-white px-6 pb-8 pt-10 sm:pt-14"><p className="text-xs font-black tracking-[.18em] text-indigo-700">MY CONSUMER STYLE</p><div className="mt-5 text-7xl">{profile.icon}</div><h1 className="mt-4 text-3xl font-black tracking-tight text-ink sm:text-5xl">{profile.name}</h1><p className="mx-auto mt-3 max-w-xl text-sm font-semibold leading-6 text-slate-600 sm:text-base">{profile.summary}</p><div className="mx-auto mt-7 grid size-36 place-items-center rounded-full p-2.5 shadow-xl" style={{background:`conic-gradient(#4f46e5 ${fitScore}%,#e0e7ff 0)`}}><div className="grid size-full place-items-center rounded-full bg-white"><span><strong className="block text-4xl font-black text-indigo-700">{fitScore}%</strong><span className="text-xs font-bold text-slate-400">유형 일치도</span></span></div></div></div><div className="px-6 pb-9 sm:px-12"><p className="mx-auto max-w-2xl leading-8 text-slate-700">{profile.description}</p>{secondary&&<p className="mt-5 rounded-2xl bg-slate-50 px-4 py-3 text-xs font-semibold text-slate-500">함께 나타난 보조 성향: <strong className="text-slate-700">{secondary.name}</strong></p>}</div></section></SectionReveal>
    <SectionReveal className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-card sm:p-9"><p className="text-xs font-black tracking-[.16em] text-indigo-600">SCORE BREAKDOWN</p><h2 className="mt-2 text-2xl font-black text-ink">소비 영역별 분석</h2><div className="mt-7 space-y-6">{domains.map(({key,label,hint})=>{const value=areaScores[key];return <div key={key}><div className="flex items-end justify-between gap-4"><div><strong className="text-sm text-slate-800">{label}</strong><p className="mt-1 text-[11px] text-slate-400">{hint}</p></div><strong className="text-indigo-700">{value}%</strong></div><div className="mt-2.5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{width:`${value}%`}} /></div></div>})}</div></SectionReveal>
    <section className="mt-7 grid gap-5 sm:grid-cols-2"><SectionReveal className="rounded-[2rem] border border-emerald-100 bg-emerald-50/70 p-6 sm:p-8"><h2 className="text-xl font-black text-emerald-950">잘 활용하고 있는 강점</h2><ul className="mt-5 space-y-3 text-sm font-semibold leading-6 text-emerald-950">{profile.strengths.map((item)=><li key={item}>✓ {item}</li>)}</ul></SectionReveal><SectionReveal className="rounded-[2rem] border border-amber-100 bg-amber-50/70 p-6 sm:p-8"><h2 className="text-xl font-black text-amber-950">주의해서 볼 부분</h2><ul className="mt-5 space-y-3 text-sm font-semibold leading-6 text-amber-950">{profile.cautions.map((item)=><li key={item}>• {item}</li>)}</ul></SectionReveal></section>
    <SectionReveal className="mt-7 rounded-[2rem] border border-indigo-100 bg-indigo-50/70 p-6 sm:p-9"><p className="text-xs font-black tracking-[.16em] text-indigo-700">NEXT ACTION</p><h2 className="mt-2 text-2xl font-black text-indigo-950">추천 콘텐츠와 실천 방법</h2><ol className="mt-6 grid gap-3 sm:grid-cols-3">{profile.recommendations.map((item,index)=><li key={item} className="rounded-2xl bg-white/90 p-5 text-sm font-bold leading-6 text-slate-700"><span className="mb-3 grid size-8 place-items-center rounded-full bg-indigo-600 text-xs text-white">{index+1}</span>{item}</li>)}</ol></SectionReveal>
    <section id="share-card" className="scroll-mt-24 mt-8 grid gap-6 rounded-[2rem] bg-slate-950 p-6 text-white sm:p-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><ShareImageCard emoji={profile.icon} eyebrow="나의 소비성향은" title={profile.name} subtitle={profile.summary} badge={`유형 일치도 ${fitScore}%`} accent="purple" /><div><h2 className="text-xl font-black">친구의 소비성향도 궁금하다면?</h2><p className="mt-2 text-sm leading-6 text-slate-300">결과를 공유하고 서로 다른 돈 쓰는 방식을 비교해 보세요.</p><div className="mt-5"><ShareButtons title={`나는 ${profile.name}! 당신의 소비성향은 어떨까요?`} description={profile.summary} path={`/result/${profile.slug}`} /></div></div></section>
    <div className="mt-8 text-center"><Link href="/tests/consumer-style-test?start=1" className="inline-flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-600 hover:bg-slate-50">다시 테스트하기</Link></div><div className="mt-7 space-y-1 text-center text-[11px] leading-5 text-slate-400"><p>이 결과는 소비 습관을 돌아보기 위한 성향 정보이며 금융상품 추천이나 투자 자문이 아닙니다.</p><p>VALS의 소비 동기·생활양식 개념만 참고했으며, 기존 문항과 유형 분류를 재현하지 않은 자체 콘텐츠입니다.</p></div>
  </div></div><MobileShareDock /></div>;
}
