"use client";
import { useState } from "react";
import Link from "next/link";
import { idealDimensions, type UserGender } from "@/data/ideal-type";
import { areaScores, calculateIdealScores, matchIdealProfile, selectIdealQuestions } from "@/lib/ideal-type-engine";
import { ShareButtons } from "@/components/share/ShareButtons";

export function IdealTypeTestPage() {
  const [gender, setGender] = useState<UserGender | null>(null); const [seed, setSeed] = useState(0); const [answers, setAnswers] = useState<Record<string,string>>({}); const [index,setIndex]=useState(0);
  if (!gender) return <main className="container-page py-12"><section className="mx-auto max-w-xl rounded-3xl bg-white p-7 text-center shadow-card sm:p-10"><span className="text-5xl">💘</span><h1 className="mt-5 text-3xl font-black text-ink">나의 이상형은 어떤 사람일까?</h1><p className="mt-4 leading-7 text-slate-600">먼저 나의 성별을 선택해 주세요. 선택한 성별에 따라 질문과 이상형 결과가 달라져요.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{([['male','남성'],['female','여성']] as const).map(([value,label])=><button key={value} onClick={()=>{setGender(value);setSeed(Date.now())}} className="min-h-16 rounded-2xl border border-rose-200 bg-rose-50 font-black text-rose-800 hover:bg-rose-100">{label}</button>)}</div></section></main>;
  const questions=selectIdealQuestions(gender,seed); const current=questions[index];
  if(Object.keys(answers).length===12){const scores=calculateIdealScores(questions,answers);const matched=matchIdealProfile(gender,scores);const areas=areaScores(scores);return <main className="container-page py-10"><div className="mx-auto max-w-3xl"><section className="rounded-[2rem] bg-gradient-to-br from-rose-600 to-violet-600 p-8 text-center text-white"><p className="text-sm font-black">내가 끌리는 이상형은</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{matched.profile.title}</h1><p className="mt-4 text-xl font-bold">이상형 일치도 {matched.match}%</p><p className="mt-4 leading-7 text-white/85">{matched.profile.shortDescription}</p></section><section className="mt-7 rounded-3xl bg-white p-6 shadow-card"><h2 className="text-2xl font-black text-ink">종합 이상형 분석</h2><p className="mt-4 leading-8 text-slate-700">{matched.profile.fullDescription}</p><div className="mt-7 space-y-4">{Object.entries(areas).map(([label,value])=><div key={label}><div className="flex justify-between text-sm font-bold"><span>{label}</span><span>{value}</span></div><div className="mt-2 h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-rose-500" style={{width:`${value}%`}}/></div></div>)}</div></section><section className="mt-7 grid gap-4 sm:grid-cols-2">{[['관계에서 기대하는 역할',matched.profile.relationshipRole],['대화와 갈등 해결',`${matched.profile.communicationStyle} ${matched.profile.conflictStyle}`],['애정과 생활 리듬',`${matched.profile.affectionStyle} ${matched.profile.lifestyle}`],['직업·분위기 이미지',`${matched.profile.occupationImages.join(' · ')}. ${matched.profile.appearanceMood}`]].map(([title,text])=><article key={title} className="rounded-3xl bg-white p-5 shadow-card"><h2 className="font-black text-ink">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</section><section className="mt-7 rounded-3xl bg-rose-50 p-6"><h2 className="text-xl font-black text-rose-950">설렘 포인트와 데이트 방식</h2><p className="mt-3 text-sm leading-7 text-rose-900">{matched.profile.attractionPoints.join(' · ')}</p><p className="mt-3 text-sm leading-7 text-rose-900">추천 데이트: {matched.profile.recommendedDates.join(' · ')}</p></section><section className="mt-7 rounded-3xl bg-slate-950 p-6 text-white"><h2 className="text-xl font-black">결과 공유하기</h2><div className="mt-5"><ShareButtons title={`내 이상형은 ${matched.profile.title}! 당신의 이상형도 확인해 보세요.`} description={matched.profile.shortDescription} path="/tests/ideal-type"/></div></section><p className="mt-7 text-center text-xs leading-6 text-slate-500">이 테스트는 일상적인 선택과 관계 취향을 바탕으로 끌릴 가능성이 높은 이상형 이미지를 재미있게 분석하는 콘텐츠입니다. 실제 연애 상대나 관계의 성공 여부를 예측하지 않습니다.</p><div className="mt-7 flex justify-center gap-3"><button onClick={()=>{setSeed(Date.now());setAnswers({});setIndex(0)}} className="rounded-xl border px-5 py-3 font-bold">다시 테스트하기</button><Link href="/tests" className="rounded-xl bg-rose-600 px-5 py-3 font-bold text-white">다른 테스트 보기</Link></div></div></main>}
  const options=current.optionOrder?[]:current.options; return <main className="container-page py-8"><div className="mx-auto max-w-2xl"><p className="text-sm font-black text-rose-600">IDEAL TYPE TEST · {index+1}/12</p><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-rose-500" style={{width:`${(index+1)/12*100}%`}}/></div><section className="mt-6 rounded-3xl bg-white p-6 shadow-card sm:p-9"><h1 className="text-2xl font-black leading-9 text-ink">{current.prompt}</h1><div className="mt-7 grid gap-3">{current.options.map((option)=><button key={option.id} onClick={()=>{const next={...answers,[current.id]:option.id};setAnswers(next);if(index<11)setTimeout(()=>setIndex(index+1),150)}} className={`min-h-16 rounded-2xl border p-4 text-left text-sm font-bold ${answers[current.id]===option.id?'border-rose-500 bg-rose-50':'border-slate-200 hover:bg-slate-50'}`}>{option.text}</button>)}</div></section><button disabled={index===0} onClick={()=>setIndex(index-1)} className="mt-4 px-3 py-2 text-sm font-bold text-slate-500 disabled:opacity-30">← 이전 질문</button></div></main>;
}
