"use client";
import Link from "next/link";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { ShareButtons } from "@/components/share/ShareButtons";
import { ShareImageCard } from "@/components/share/ShareImageCard";
import { MobileShareDock } from "@/components/share/MobileShareDock";
import { SectionReveal } from "@/components/motion/SectionReveal";
import { AdRectangle } from "@/components/ads/AdRectangle";
import { jobStressDisclaimer,jobStressFactors,jobStressLevels } from "@/data/job-stress";
import type { JobStressFactor,JobStressFactorProfile,JobStressLevel } from "@/data/job-stress";

type Props={level:JobStressLevel;overallScore:number|null;factorScores:Record<JobStressFactor,number>|null;primaryFactors:JobStressFactorProfile[];stableFactor:JobStressFactorProfile|null;encodedAnswers:string|null};
type GtagWindow=Window&{gtag?:(command:string,event:string)=>void}; const track=(event:string)=>{if(typeof window!=="undefined")(window as GtagWindow).gtag?.("event",event);};
export function JobStressResult({level,overallScore,factorScores,primaryFactors,stableFactor,encodedAnswers}:Props){
 const score=overallScore??Math.round((level.minScore+level.maxScore)/2),primaryTitle=primaryFactors.map((item)=>item.resultTitle).join(" + "); const path=`/job-stress/result/${level.id}${encodedAnswers?`?a=${encodedAnswers}`:""}`;
 const personal=[...new Set(primaryFactors.flatMap((item)=>item.personalActions))].slice(0,5),organization=[...new Set(primaryFactors.flatMap((item)=>item.organizationalActions))].slice(0,5);
 const restart=()=>{track("job_stress_test_restart");sessionStorage.removeItem("mimi-job-stress-progress");location.href="/tests/job-stress?start=1";};
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#dbeafe_0,#eef2ff_34%,#f8fafc_100%)] pb-24 pt-8 sm:py-14"><div className="container-page"><Breadcrumbs items={[{name:"테스트",href:"/tests"},{name:"직무 스트레스 테스트",href:"/tests/job-stress"},{name:level.title}]}/><div className="mx-auto max-w-4xl"><SectionReveal><section className="overflow-hidden rounded-3xl border border-indigo-100 bg-white text-center shadow-card"><div className="bg-gradient-to-b from-indigo-50 to-white px-6 pb-7 pt-10"><p className="text-sm font-extrabold text-indigo-600">나의 직무 스트레스 점수</p><div className="mt-4 text-7xl" role="img" aria-label={`${level.title} 대표 아이콘`}>{level.icon}</div><div className="mx-auto mt-5 grid size-36 place-items-center rounded-full p-2 shadow-lg" style={{background:`conic-gradient(#4f46e5 ${score}%,#e0e7ff 0)`}}><div className="grid size-full place-items-center rounded-full bg-white"><strong className="text-4xl font-black tabular-nums text-indigo-600">{score}<span className="text-lg">점</span></strong></div></div><h1 className="mt-5 text-3xl font-black text-ink sm:text-4xl">{level.title}</h1><p className="mx-auto mt-3 max-w-xl font-semibold text-slate-600">{level.summary}</p><p className="mx-auto mt-5 max-w-2xl text-left leading-7 text-slate-700">{level.description}</p><p className="mt-5 text-xs text-slate-400">미미테스트의 자체 문항과 계산 기준을 적용한 자기이해용 점수입니다.</p></div></section></SectionReveal><AdRectangle/>
 {primaryFactors.length>0?<SectionReveal className="mt-8 rounded-3xl border border-indigo-100 bg-indigo-50/70 p-6 sm:p-8"><h2 className="text-xl font-black text-indigo-950">주요 직무 스트레스 원인</h2><div className={`mt-5 grid gap-4 ${primaryFactors.length>1?"sm:grid-cols-2":""}`}>{primaryFactors.map((factor)=><article key={factor.id} className="rounded-2xl bg-white p-5 shadow-sm"><strong className="text-lg font-black text-indigo-700">{factor.resultTitle}</strong><p className="mt-2 text-sm leading-6 text-slate-700">{factor.description}</p></article>)}</div></SectionReveal>:<SectionReveal className="mt-8 rounded-3xl border border-emerald-100 bg-emerald-50 p-6"><h2 className="font-black text-emerald-900">전반적으로 안정적인 편입니다</h2><p className="mt-2 text-sm leading-6 text-emerald-800">특정 영역에 스트레스가 집중되기보다 현재 업무 조건이 비교적 고르게 유지되고 있어요.</p></SectionReveal>}
 <SectionReveal className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-card sm:p-8"><h2 className="text-xl font-black text-ink">8개 영역별 점수</h2><p className="mt-2 text-xs leading-5 text-slate-500">점수가 높을수록 해당 영역에서 체감하는 직무 스트레스 요인이 크다는 의미입니다.</p>{factorScores?<div className="mt-6 grid gap-4">{jobStressFactors.map((factor)=>{const value=factorScores[factor.id];return <div key={factor.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3 text-sm font-black"><span>{factor.title}</span><span className="tabular-nums text-indigo-600">{value}점</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white" role="img" aria-label={`${factor.title} 스트레스 ${value}점`}><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-violet-500 motion-reduce:transition-none" style={{width:`${value}%`}}/></div></div>})}</div>:<p className="mt-5 text-sm text-slate-500">테스트를 완료하면 영역별 점수가 표시됩니다.</p>}</SectionReveal>
 {stableFactor&&<SectionReveal className="mt-8 rounded-3xl border border-emerald-100 bg-white p-6 sm:p-8"><h2 className="text-xl font-black text-ink">비교적 안정적인 영역: {stableFactor.title}</h2><p className="mt-3 leading-7 text-slate-700">{stableFactor.stableDescription} 낮은 점수라고 해서 문제가 전혀 없다는 뜻은 아니지만, 현재 직장생활에서 활용할 수 있는 보호 조건으로 볼 수 있습니다.</p></SectionReveal>}
 <section className="mt-8 grid gap-5 lg:grid-cols-2"><SectionReveal className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><h2 className="text-lg font-black text-ink">내가 직접 점검할 수 있는 부분</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-700">{(personal.length?personal:["부담이 높아지는 시간과 상황을 짧게 기록하기","현재 잘 유지되는 회복 습관을 지속하기","혼자 해결하기 어려운 문제를 구분하기"]).map((item)=><li key={item}>✓ {item}</li>)}</ul></SectionReveal><SectionReveal className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><h2 className="text-lg font-black text-ink">조직과 협의할 수 있는 부분</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-700">{(organization.length?organization:["정기적인 피드백과 업무 조건 점검 요청하기","필요한 자원과 지원 채널을 미리 확인하기","업무 변화에 대한 사전 공유 방식 제안하기"]).map((item)=><li key={item}>✓ {item}</li>)}</ul></SectionReveal></section>
 {score>=60&&<aside className="mt-8 rounded-3xl border border-amber-200 bg-amber-50 p-6 text-sm leading-7 text-amber-950"><strong>높은 점수 결과 안내</strong><p className="mt-2">높은 점수는 최근 직장환경에서 부담을 크게 느끼고 있을 가능성을 보여줍니다. 이 결과만으로 건강 상태나 질환을 판단할 수는 없습니다. 업무 수행이나 일상생활에 어려움이 계속된다면 회사의 고충처리 담당자, 근로자 지원 프로그램, 산업보건 담당자 또는 관련 전문가의 도움을 검토해 보세요.</p></aside>}
 <section id="share-card" className="mt-10 grid gap-6 rounded-3xl bg-ink p-6 text-white sm:p-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center" onClickCapture={()=>track("job_stress_test_share")}><ShareImageCard emoji={level.icon} eyebrow="직무 스트레스 테스트" title={`${score}점 · ${level.title}`} subtitle={primaryTitle?`주요 원인: ${primaryTitle}`:level.summary} badge={`직무 스트레스 ${score}점`} accent="blue"/><div><h2 className="text-xl font-black">내 직장 스트레스 원인은 무엇이었을까?</h2><p className="mt-2 text-sm leading-6 text-slate-300">점수와 결과 단계만 공유되며 개별 답변은 포함되지 않습니다.</p><div className="mt-5"><ShareButtons title={`내 직무 스트레스 점수는 ${score}점, ${primaryTitle||level.title}이었어요.`} description={level.summary} path={path}/></div></div></section>
 <div className="mt-8 flex flex-wrap justify-center gap-3"><button type="button" onClick={restart} className="inline-flex min-h-12 items-center rounded-xl bg-primary px-6 text-sm font-black text-white">다시 테스트하기</button><Link href="/tests/turnover-intention" className="inline-flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-600">이직 의향 테스트</Link><Link href="/tests/burnout-risk-test" className="inline-flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-600">번아웃 테스트</Link><Link href="/tests/work-persona-16" className="inline-flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-600">직장 MBTI 테스트</Link></div>
 <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-black text-ink">결과 단계 기준</h2><ul className="mt-4 grid gap-2 sm:grid-cols-5">{jobStressLevels.map((item)=><li key={item.id} className={`rounded-xl border p-3 text-center text-xs font-bold ${item.id===level.id?"border-indigo-400 bg-indigo-50":"border-slate-200"}`}>{item.minScore}~{item.maxScore}<br/>{item.title}</li>)}</ul></section><p className="mx-auto mt-8 max-w-3xl text-center text-xs leading-6 text-slate-400">{jobStressDisclaimer}</p></div></div><MobileShareDock/></div>;
}
