"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { AnimatePresence,motion,useReducedMotion } from "framer-motion";
import { JOB_STRESS_QUESTION_COUNT,jobStressAnswerLabels,jobStressMeasurementGuide,jobStressQuestions } from "@/data/job-stress";
import { calculateJobStressResult,encodeJobStressAnswers,firstUnansweredJobStress,type JobStressAnswer } from "@/lib/job-stress-engine";

const SESSION_KEY="mimi-job-stress-progress";
type GtagWindow=Window&{gtag?:(command:string,event:string,params?:Record<string,number>)=>void};
const track=(event:string,params?:Record<string,number>)=>{ if(typeof window!=="undefined")(window as GtagWindow).gtag?.("event",event,params); };

export function JobStressTestPage(){
 const router=useRouter(),reduceMotion=useReducedMotion(); const [answers,setAnswers]=useState<(JobStressAnswer|undefined)[]>([]),[index,setIndex]=useState(0),[locked,setLocked]=useState(false); const started=useRef(false);
 useEffect(()=>{let stored:{answers?:(JobStressAnswer|null)[];index?:number}|null=null;try{stored=JSON.parse(sessionStorage.getItem(SESSION_KEY)??"null");}catch{} if(stored?.answers)setAnswers(stored.answers.map((v)=>v===null?undefined:v));if(typeof stored?.index==="number")setIndex(Math.min(stored.index,31));if(!started.current){started.current=true;track("job_stress_test_start");}},[]);
 const persist=(next:(JobStressAnswer|undefined)[],nextIndex:number)=>{try{sessionStorage.setItem(SESSION_KEY,JSON.stringify({answers:next.map((v)=>v??null),index:nextIndex}));}catch{}};
 const question=jobStressQuestions[index],selected=answers[index],progress=Math.round((index+1)/JOB_STRESS_QUESTION_COUNT*100);
 const choose=(value:JobStressAnswer)=>{if(locked||!question)return;const next=answers.slice();next[index]=value;setAnswers(next);setLocked(true);track("job_stress_test_answer",{questionNumber:index+1});window.setTimeout(()=>{setLocked(false);if(index<31){setIndex(index+1);persist(next,index+1);return;}const missing=firstUnansweredJobStress(next);if(missing!==null){setIndex(missing);persist(next,missing);return;}const complete=next as JobStressAnswer[];const result=calculateJobStressResult(complete);track("job_stress_test_complete");sessionStorage.removeItem(SESSION_KEY);router.push(`/job-stress/result/${result.level.id}?a=${encodeJobStressAnswers(complete)}`);},reduceMotion?0:240);};
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.metaKey||event.ctrlKey||event.altKey)return;const value=Number(event.key)-1;if(value>=0&&value<=3)choose(value as JobStressAnswer);};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);});
 const back=()=>{const previous=Math.max(0,index-1);setIndex(previous);persist(answers,previous);}; if(!question)return null;
 return <main className="min-h-[calc(100vh-5rem)] bg-[radial-gradient(circle_at_top,#dbeafe_0,#eef2ff_42%,#f8fafc_100%)] py-6 sm:py-12"><div className="container-page mx-auto max-w-2xl"><header className="mb-6"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.16em] text-indigo-600">JOB STRESS CHECK</p><h1 className="mt-2 text-xl font-black text-ink sm:text-2xl">직무 스트레스 테스트</h1></div><strong className="shrink-0 text-sm text-slate-500">{index+1} / 32</strong></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white shadow-inner" role="progressbar" aria-label="테스트 진행률" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><motion.div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-violet-500" animate={{width:`${Math.max(progress,3)}%`}} transition={{duration:reduceMotion?0:.3}}/></div><p className="mt-3 rounded-xl bg-indigo-50 px-4 py-2.5 text-xs font-bold leading-5 text-indigo-900">{jobStressMeasurementGuide}</p></header><AnimatePresence mode="wait"><motion.section key={question.id} initial={reduceMotion?false:{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={reduceMotion?undefined:{opacity:0,x:-20}} className="rounded-[2rem] border border-white/90 bg-white/95 p-6 shadow-2xl shadow-indigo-100/60 sm:p-10"><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-black text-indigo-700">질문 {index+1}</span><h2 className="mt-6 min-h-20 text-balance text-xl font-black leading-[1.5] text-ink sm:text-2xl">{question.text}</h2><div className="mt-8 grid gap-2.5" role="radiogroup" aria-label="답변 선택, 숫자키 1부터 4까지 사용 가능">{jobStressAnswerLabels.map((label,value)=>{const active=selected===value;return <motion.button key={label} type="button" role="radio" aria-checked={active} aria-label={`${value+1}번: ${label}`} disabled={locked} onClick={()=>choose(value as JobStressAnswer)} whileTap={reduceMotion?undefined:{scale:.98}} className={`flex min-h-14 items-center gap-4 rounded-2xl border px-4 text-left text-sm font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 disabled:cursor-wait sm:px-5 ${active?"border-indigo-500 bg-indigo-50 text-indigo-900 shadow-md":"border-slate-200 bg-white text-slate-700 hover:border-indigo-300 hover:bg-indigo-50/50"}`}><span className={`grid size-8 shrink-0 place-items-center rounded-full text-xs font-black ${active?"bg-indigo-600 text-white":"bg-slate-100 text-slate-500"}`}>{value+1}</span>{label}</motion.button>})}</div></motion.section></AnimatePresence><div className="mt-5 flex items-center justify-between gap-4"><button type="button" onClick={back} disabled={index===0||locked} className="min-h-12 rounded-xl px-4 text-sm font-bold text-slate-500 hover:bg-white disabled:opacity-30">← 이전 문항</button><p className="text-right text-[11px] leading-5 text-slate-400">키보드 1~4로도 답할 수 있어요.<br/>답변은 서버에 저장되지 않습니다.</p></div></div></main>;
}
