import Link from "next/link";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { SectionReveal } from "@/components/motion/SectionReveal";
import { ShareButtons } from "@/components/share/ShareButtons";
import { ShareImageCard } from "@/components/share/ShareImageCard";
import { MobileShareDock } from "@/components/share/MobileShareDock";
import { getLoveCompatibility, type CompatibilityTier } from "@/data/love-compatibility";
import { getLoveLanguageLabel } from "@/lib/love-mbti-engine";
import type { LoveDomainScores, LoveLanguage, LoveLanguageScores, LoveResultProfile } from "@/lib/types";

const domains=[{key:"stability",label:"애착 안정성",hint:"불안에 휩쓸리지 않고 신뢰를 유지하는 정도"},{key:"expression",label:"감정 표현력",hint:"애정과 서운함을 솔직하게 나누는 정도"},{key:"leadership",label:"관계 주도성",hint:"데이트와 관계의 방향을 먼저 제안하는 정도"},{key:"independence",label:"독립성",hint:"연애와 개인 생활의 균형을 중시하는 정도"},{key:"loveLanguage",label:"애정 표현 감응도",hint:"다양한 방식의 애정 표현에 의미를 두는 정도"}] as const;
const languages:LoveLanguage[]=["words","time","gifts","acts","touch"];
const tierMeta:Record<CompatibilityTier,{icon:string;title:string;classes:string}>={best:{icon:"❤️",title:"최고의 궁합",classes:"border-rose-100 bg-rose-50/70"},good:{icon:"😊",title:"좋은 궁합",classes:"border-violet-100 bg-violet-50/70"},caution:{icon:"⚠️",title:"주의가 필요한 궁합",classes:"border-amber-100 bg-amber-50/70"}};

export function LoveMbtiResult({profile,secondary,fitScore,areaScores,languageScores,primaryLoveLanguage}:{profile:LoveResultProfile;secondary?:LoveResultProfile;fitScore:number;areaScores:LoveDomainScores;languageScores:LoveLanguageScores;primaryLoveLanguage:LoveLanguage}){
  const compatibility=getLoveCompatibility(profile.slug);
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#ffe4e6_0,#faf5ff_34%,#f8fafc_100%)] pb-24 pt-8 sm:py-14"><div className="container-page"><Breadcrumbs items={[{name:"테스트",href:"/tests"},{name:"연애 MBTI 결과"}]} /><div className="mx-auto max-w-4xl">
    <SectionReveal><section className="overflow-hidden rounded-[2rem] border border-white bg-white/90 text-center shadow-2xl shadow-rose-100/70 backdrop-blur"><div className="bg-gradient-to-b from-rose-50 via-violet-50/60 to-white px-6 pb-8 pt-10 sm:pt-14"><p className="text-xs font-black tracking-[.18em] text-rose-600">MY LOVE TYPE</p><div className="mt-5 text-7xl" aria-hidden="true">{profile.icon}</div><p className="mt-4 text-sm font-black text-rose-600">당신은 사랑할 때</p><h1 className="mt-1 text-4xl font-black tracking-tight text-ink sm:text-6xl">{profile.name}</h1><p className="mx-auto mt-3 max-w-xl text-sm font-semibold leading-6 text-slate-600 sm:text-base">{profile.summary}</p><div className="mx-auto mt-7 grid size-36 place-items-center rounded-full p-2.5 shadow-xl" style={{background:`conic-gradient(#e11d48 ${fitScore}%,#ffe4e6 0)`}}><div className="grid size-full place-items-center rounded-full bg-white"><span><strong className="block text-4xl font-black text-rose-600">{fitScore}%</strong><span className="text-xs font-bold text-slate-400">유형 일치도</span></span></div></div><span className="mt-6 inline-flex rounded-full bg-white px-4 py-2 text-sm font-black text-violet-700 shadow-md">💌 대표 사랑의 언어 · {getLoveLanguageLabel(primaryLoveLanguage)}</span></div><div className="px-6 pb-9 sm:px-12"><p className="mx-auto max-w-2xl text-left leading-8 text-slate-700 sm:text-center">{profile.description}</p>{secondary&&<p className="mt-5 rounded-2xl bg-slate-50 px-4 py-3 text-xs font-semibold text-slate-500">함께 나타난 보조 성향: <strong className="text-slate-700">{secondary.name}</strong></p>}</div></section></SectionReveal>

    <SectionReveal className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-card sm:p-9"><p className="text-xs font-black tracking-[.16em] text-rose-600">RELATIONSHIP STYLE</p><h2 className="mt-2 text-2xl font-black text-ink">나의 연애 방식</h2><p className="mt-5 leading-8 text-slate-700">{profile.relationshipStyle}</p><div className="mt-6 flex flex-wrap gap-2">{profile.traits.map((trait)=><span key={trait} className="rounded-full bg-rose-50 px-4 py-2 text-xs font-black text-rose-700">#{trait}</span>)}</div></SectionReveal>

    <SectionReveal className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-card sm:p-9"><p className="text-xs font-black tracking-[.16em] text-violet-600">LOVE STATS</p><h2 className="mt-2 text-2xl font-black text-ink">영역별 연애 성향</h2><div className="mt-7 space-y-6">{domains.map(({key,label,hint})=>{const value=areaScores[key];return <div key={key}><div className="flex items-end justify-between gap-4"><div><strong className="text-sm text-slate-800">{label}</strong><p className="mt-1 text-[11px] text-slate-400">{hint}</p></div><strong className="text-rose-600">{value}%</strong></div><div className="mt-2.5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-rose-500 to-violet-500" style={{width:`${value}%`}} /></div></div>})}</div></SectionReveal>

    <SectionReveal className="mt-7 rounded-[2rem] border border-violet-100 bg-violet-50/60 p-6 sm:p-9"><h2 className="text-2xl font-black text-violet-950">내가 사랑을 느끼는 방식</h2><p className="mt-2 text-sm leading-6 text-violet-800">한 가지 방식만 정답은 아닙니다. 점수가 높은 표현부터 상대와 구체적으로 나눠보세요.</p><div className="mt-6 grid gap-3 sm:grid-cols-5">{languages.map((language)=><div key={language} className={`rounded-2xl bg-white p-4 text-center shadow-sm ${language===primaryLoveLanguage?"ring-2 ring-rose-400":""}`}><p className="text-xs font-black text-slate-700">{getLoveLanguageLabel(language)}</p><strong className="mt-2 block text-xl text-violet-700">{languageScores[language]}%</strong></div>)}</div></SectionReveal>

    <section className="mt-7 grid gap-5 sm:grid-cols-2"><SectionReveal className="rounded-[2rem] border border-emerald-100 bg-emerald-50/70 p-6 sm:p-8"><h2 className="text-xl font-black text-emerald-950">연애에서 빛나는 강점</h2><ul className="mt-5 space-y-3 text-sm font-semibold leading-6 text-emerald-950">{profile.strengths.map((item)=><li key={item}>✓ {item}</li>)}</ul></SectionReveal><SectionReveal className="rounded-[2rem] border border-amber-100 bg-amber-50/70 p-6 sm:p-8"><h2 className="text-xl font-black text-amber-950">조심하면 좋은 부분</h2><ul className="mt-5 space-y-3 text-sm font-semibold leading-6 text-amber-950">{profile.cautions.map((item)=><li key={item}>• {item}</li>)}</ul></SectionReveal></section>
    <SectionReveal className="mt-7 rounded-[2rem] bg-slate-950 p-6 text-white sm:p-9"><p className="text-xs font-black tracking-[.16em] text-rose-300">IDEAL PARTNER</p><h2 className="mt-2 text-2xl font-black">잘 맞는 파트너의 모습</h2><p className="mt-4 leading-8 text-slate-200">{profile.idealPartner}</p></SectionReveal>

    <section className="mt-10"><p className="text-xs font-black tracking-[.16em] text-rose-600">LOVE COMPATIBILITY</p><h2 className="mt-2 text-3xl font-black text-ink">8개 유형 궁합 분석</h2><p className="mt-3 text-sm leading-6 text-slate-500">궁합 점수는 관계의 성공률이 아니라 소통 방식이 자연스럽게 맞물리는 정도를 뜻합니다.</p><div className="mt-7 space-y-6">{(Object.keys(tierMeta) as CompatibilityTier[]).map((tier)=>{const meta=tierMeta[tier];return <SectionReveal key={tier} className={`rounded-[2rem] border p-5 sm:p-7 ${meta.classes}`}><h3 className="text-xl font-black text-ink">{meta.icon} {meta.title}</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{compatibility[tier].map(({partner,score,description})=><article key={partner.slug} className="rounded-2xl bg-white/90 p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><span className="text-3xl">{profile.icon} × {partner.icon}</span><h4 className="mt-2 font-black text-ink">{profile.name} × {partner.name}</h4></div><strong className="shrink-0 text-xl text-rose-600">{score}%</strong></div><p className="mt-4 text-sm leading-6 text-slate-600">{description}</p><Link href={`/result/${partner.slug}`} className="mt-4 inline-flex text-xs font-black text-violet-700">{partner.name} 결과 보기 →</Link></article>)}</div></SectionReveal>})}</div></section>

    <section id="share-card" className="scroll-mt-24 mt-10 grid gap-6 rounded-[2rem] bg-gradient-to-br from-rose-600 to-violet-700 p-6 text-white shadow-xl sm:p-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><ShareImageCard emoji={profile.icon} eyebrow="나의 연애 MBTI는" title={profile.name} subtitle={`최고의 궁합 · ${compatibility.best[0].partner.name}`} badge={`유형 일치도 ${fitScore}%`} accent="pink" /><div><h2 className="text-xl font-black">우리 둘의 연애 유형도 비교해볼까요?</h2><p className="mt-2 text-sm leading-6 text-rose-50">내 결과를 공유하고 상대의 유형과 궁합을 확인해 보세요.</p><div className="mt-5 rounded-2xl bg-white/10 p-2"><ShareButtons title={`나는 ${profile.name}! 최고의 궁합은 ${compatibility.best[0].partner.name}이라고 합니다.`} description="당신의 연애 유형은 무엇인가요?" path={`/result/${profile.slug}`} /></div></div></section>
    <div className="mt-8 text-center"><Link href="/tests/love-mbti-test?start=1" className="inline-flex min-h-12 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-600 hover:bg-slate-50">다시 테스트하기</Link></div><div className="mt-7 space-y-1 text-center text-[11px] leading-5 text-slate-400"><p>이 결과는 관계 성향을 돌아보기 위한 콘텐츠이며 심리 진단이나 관계의 성공을 예측하는 검사가 아닙니다.</p><p>사랑의 언어 점수는 표현 선호를 대화하기 위한 보조 지표이며, 같은 언어끼리의 관계 만족도를 보장하지 않습니다.</p><p>애착 이론과 애정 표현 선호 개념을 참고했지만 기존 검사 문항을 사용하지 않은 자체 콘텐츠입니다.</p></div>
  </div></div><MobileShareDock /></div>;
}
